name: "API Contract: Postman Validation"

on:
  push:
    branches: [ main, master ]
  # También puedes activarlo manualmente desde GitHub
  workflow_dispatch: 

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run email-api/auth-mailer.json \
          --reporters cli \
          --env-var "https://moviesapp-lc0z.onrender.com"
